# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{translated_attributes}
  s.version = "0.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2011-08-04}
  s.email = %q{michael@grosser.it}
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "init.rb",
    "lib/generators/translated_attributes/USAGE",
    "lib/generators/translated_attributes/templates/migration.rb",
    "lib/generators/translated_attributes/translated_attributes_generator.rb",
    "lib/translated_attributes.rb",
    "lib/translated_attributes/caching.rb",
    "spec/integration_spec.rb",
    "spec/models.rb",
    "spec/spec_helper.rb",
    "spec/translated_attributes_spec.rb",
    "translated_attributes.gemspec"
  ]
  s.homepage = %q{http://github.com/grosser/translated_attributes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{ActiveRecord/Rails simple translatable attributes}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

